kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ghcr.io/tystuyfzand/precise-go
      registry: ghcr.io
      tags:
        - latest
        - ubuntu-jammy
    depends_on:
      - clone
  - name: docker-gpu
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        BASE_IMAGE: nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04
      repo: ghcr.io/tystuyfzand/precise-go
      registry: ghcr.io
      tags:
        - ubuntu-jammy-gpu
        - latest-gpu
  - name: docker-debian
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        BASE_IMAGE: debian:bullseye
      repo: ghcr.io/tystuyfzand/precise-go
      registry: ghcr.io
      tags:
        - debian
    depends_on:
      - clone
